// Chord shapes: low E -> high e, null = muted. `bass` lists the string indexes boom-chuck alternates through;
// `thumb` marks a low-E note fretted with the thumb. Chords not listed here come from ../chords.mjs.
const q = s => `"${s}"`;
// Outro fingerpicking, played twice per bar in 16ths.
const travisC = ['(3.5 1.2)', '0.3', '2.4', '1.2', '3.6', '0.3', '2.4', '1.2'];
const pickDdim = ['(0.4 3.2)', '1.3', '0.4', '3.2', '0.4', '1.3', '0.4', '3.2'];
const pick = (chord, notes) => [...notes, ...notes]
  .map((n, i) => `${n.replace(/(\d+\.\d)/g, '$1{lr}')}.16${i === 0 ? ` {ch ${q(chord)}}` : ''}`)
  .join(' ');

export default {
  title: 'Nothing on This Earth Can Make Me Smile',
  artist: 'Dougie Poole',
  capo: 2,
  key: 'D',
  tempo: 80,
  pattern: 'boomChuck',
  note: '<b>Thumb over the neck.</b> F, F/G, Am6/F#, Am/F# and A♭dim fret the low E string with your thumb wrapped over the top of the neck (marked <b>T</b> in the chord boxes). Your fingers then handle the D, G and B strings. The shapes look impossible as normal fingerings, but they\'re right.',
  chords: {
    'C/G':       { frets: [3,3,2,0,1,null], bass: [1, 0] },
    'Cmaj7/G':   { frets: [3,3,2,0,0,null], bass: [1, 0] },
    'Ddim7':     { frets: [null,5,6,4,6,null] },
    'C (barre)': { frets: [null,3,5,5,5,null] },
    'Cmaj7':     { frets: [null,3,5,4,5,null] },
    'C7':        { frets: [null,3,5,3,5,null] },
    'Am6':       { frets: [null,0,4,2,1,null] },
    'Am6/F#':    { frets: [2,null,4,2,1,null], thumb: true },
    'F':         { frets: [1,null,3,2,1,null], thumb: true },
    'F/G':       { frets: [3,null,3,2,1,null], thumb: true },
    'C':         { frets: [null,3,2,0,1,null] },
    'Gadd4/B':   { frets: [null,2,0,0,1,null] },
    'Em7':       { frets: [0,null,2,0,3,null] },
    'Cadd9':     { frets: [null,3,2,0,3,null] },
    'Am':        { frets: [null,0,2,2,1,null] },
    'Am/F#':     { frets: [2,null,2,2,1,null], thumb: true },
    'A♭dim':     { frets: [4,null,0,4,3,null], thumb: true },
    'Ddim':      { frets: [null,null,0,1,3,null] },
  },
  // [chord|null, quarter beats, verse 1 lyric, verse 2 lyric]; { raw } is literal alphaTex.
  bars: [
    { ac: true, beats: [[null, 1, 'I seen the']] },
    { repeatStart: true, beats: [['C/G', 2, '1. plague of', '2. sweetest thing'], ['Cmaj7/G', 2, 'locusts, the', "that I've"]] },
    { beats: [['Ddim7', 2, 'plague of', 'ever'], ['C (barre)', 2, "lice, an", 'seen']] },
    { beats: [['C (barre)', 1, 'ocean', 'A photo-'], ['C (barre)', 1, 'split right', 'cake, for'], ['Cmaj7', 1, 'down the', 'goodness'], ['C7', 1, 'middle', 'sake']] },
    { beats: [['Am6', 2, "Ain't that", 'Devotion iced in'], ['Am6/F#', 2, 'nice, oh honey', 'green, oh, honey']] },
    { beats: [['F', 2, "Nothin' on this", 'nothing on this'], ['F/G', 2, 'earth could make me', 'earth can make me']] },
    { beats: [['C', 1, 'smile,', 'smile,'], ['Gadd4/B', 1, 'I', 'I'], ['Am6/F#', 1, 'told ya', 'told you'], ['Am6/F#', 1]] },
    { beats: [['F', 2, "Nothin' on this", 'nothing on this'], ['F/G', 2, 'earth could make me', 'earth can make me']] },
    { ending: 1, beats: [['C/G', 4, 'smile']] },
    { ending: 1, repeatEnd: 2, beats: [['C/G', 2], ['C/G', 2, "Well it's the"]] },
    { ending: 2, beats: [['C/G', 3, '', 'smile'], { raw: '3.5.8 2.5.8' }] },
    { beats: [['Am', 2, 'ooh'], ['Am/F#', 2]] },
    { beats: [['Am', 2, 'ooh'], ['Am/F#', 2]] },
    { beats: [['F', 2, 'ooh'], ['Em7', 2]] },
    { beats: [['C', 2, 'ooh'], ['Cadd9', 2]] },
    { beats: [['Am', 2, 'ooh'], ['Am/F#', 2]] },
    { beats: [['Am', 2, 'ooh'], ['Am/F#', 2]] },
    { beats: [['F', 2, 'ooh'], ['Em7', 2]] },
    { beats: [['F', 2], ['A♭dim', 2]] },
    { doubleBar: true, beats: [['C/G', 3], ['C/G', 1, 'I like my']] },
    { beats: [['C/G', 2, 'toast with'], ['Cmaj7/G', 2, 'jam, love, my']] },
    { beats: [['Ddim7', 2, 'coffee'], ['C (barre)', 2, 'mild. My']] },
    { beats: [['C (barre)', 1, 'troubles'], ['C (barre)', 1, 'stacked like'], ['Cmaj7', 1, 'dishes'], ['C7', 1, 'in a']] },
    { beats: [['Am6', 2, 'crooked'], ['Am6/F#', 2, 'pile, and']] },
    { beats: [['F', 2, 'nothing on this'], ['F/G', 2, 'earth can make me']] },
    { beats: [['C', 1, 'smile,'], ['Gadd4/B', 1, 'no,'], ['Am6/F#', 1, 'no'], ['Am6/F#', 1]] },
    { beats: [['F', 2, 'nothing on this'], ['F/G', 2, 'earth can make me']] },
    { beats: [['C', 1, 'smile,'], ['Gadd4/B', 1, 'I'], ['Am6/F#', 1, 'told you'], ['Am6/F#', 1]] },
    { beats: [['F', 2, 'nothing on this'], ['F/G', 2, 'earth can make me']] },
    { doubleBar: true, beats: [['C/G', 4, 'smile']] },
    { beats: [{ raw: pick('C/G', travisC) }] },
    { beats: [{ raw: pick('Ddim', pickDdim) }] },
    { beats: [{ raw: pick('C/G', travisC) }] },
    { beats: [{ raw: pick('Ddim', pickDdim) }] },
    { beats: [{ raw: '(3.5 2.4 0.3 1.2).1 {ch "C/G"}' }] },
  ],
  sheet: [
    ['Verse 1', [
      [[null, 'I seen the '], ['C/G', 'plague of '], ['Cmaj7/G', 'locusts, the']],
      [['Ddim7', 'plague of '], ['C (barre)', "lice, an"]],
      [['C (barre)', 'ocean split right '], ['Cmaj7', 'down the '], ['C7', 'middle']],
      [['Am6', "Ain't that "], ['Am6/F#', 'nice, oh honey']],
      [['F', "Nothin' on this "], ['F/G', 'earth could make me']],
      [['C', 'smile, '], ['Gadd4/B', 'I '], ['Am6/F#', 'told ya']],
      [['F', "Nothin' on this "], ['F/G', 'earth could make me']],
      [['C/G', 'smile']],
    ]],
    ['Verse 2', [
      [[null, "Well it's the "], ['C/G', 'sweetest thing '], ['Cmaj7/G', "that I've"]],
      [['Ddim7', 'ever '], ['C (barre)', 'seen']],
      [['C (barre)', 'A photo-cake, for '], ['Cmaj7', 'goodness '], ['C7', 'sake']],
      [['Am6', 'Devotion iced in '], ['Am6/F#', 'green, oh, honey']],
      [['F', 'nothing on this '], ['F/G', 'earth can make me']],
      [['C', 'smile, '], ['Gadd4/B', 'I '], ['Am6/F#', 'told you']],
      [['F', 'nothing on this '], ['F/G', 'earth can make me']],
      [['C/G', 'smile']],
      '(bass walks C–B into the interlude)',
    ]],
    ['Interlude', [
      [['Am', 'ooh '], ['Am/F#', ''], ['Am', 'ooh '], ['Am/F#', '']],
      [['F', 'ooh '], ['Em7', ''], ['C', 'ooh '], ['Cadd9', '']],
      [['Am', 'ooh '], ['Am/F#', ''], ['Am', 'ooh '], ['Am/F#', '']],
      [['F', 'ooh '], ['Em7', ''], ['F', ''], ['A♭dim', '']],
      [['C/G', '']],
    ]],
    ['Verse 3', [
      [[null, 'I like my '], ['C/G', 'toast with '], ['Cmaj7/G', 'jam, love, my']],
      [['Ddim7', 'coffee '], ['C (barre)', 'mild. My']],
      [['C (barre)', 'troubles stacked like '], ['Cmaj7', 'dishes '], ['C7', 'in a']],
      [['Am6', 'crooked '], ['Am6/F#', 'pile, and']],
      [['F', 'nothing on this '], ['F/G', 'earth can make me']],
      [['C', 'smile, '], ['Gadd4/B', 'no, '], ['Am6/F#', 'no']],
      [['F', 'nothing on this '], ['F/G', 'earth can make me']],
      [['C', 'smile, '], ['Gadd4/B', 'I '], ['Am6/F#', 'told you']],
      [['F', 'nothing on this '], ['F/G', 'earth can make me']],
      [['C/G', 'smile']],
    ]],
    ['Outro', [
      [['C/G', ''], ['Ddim', ''], ['C/G', ''], ['Ddim', ''], ['C/G', '']],
      '(fingerpicked in 16ths)',
    ]],
  ],
};
